on:
  push:
    branches:
      - dev-env-1

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🔨 Build Project
        run: |
          composer install --no-dev
          php artisan optimize
          php artisan config:clear

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.dev.funnelliner.com
          username: main@dev.funnelliner.com
          password: 6Th@;_j=-rft
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
