name: Publish Website to Web Hosting
on:
  push:
    branches:
      - dev-env-1
jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Install Packages
        run: composer install --no-dev
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.funnelliner.com
          username: dev@dev.funnelliner.com
          password: &IACUiD-rW~Q
          protocol: ftps
          port: 21 # todo replace with your web hosts ftps port
